### ISSUE TITLE
Latest gvisor incompatiblity in PacketBuffer

### ISSUE THREAD

**Issue by elliottneilclark** [noisysockets/noisysockets#2]
https://github.com/google/gvisor/commit/3c75945fd6546f6f20f5ace5b002d2481b24dae0 IsNil was removed from PacketBuffer. This causes `go get -u ./... && go mod tidy && go build your mod` on a module that depends on noisysockets to break.

Meaning that:
https://github.com/noisysockets/noisysockets/blob/ec59aeb79c11b744bc40876402a4f63b4b894792/source_sink.go#L247

Should now read `if pkt == nil`

**Comment by dpeckett** [comment]
Thanks Elliot for chasing up the original gVisor commit (gives a lot of context into the why).

I've bumped the gVisor dependency and pushed a patch release `v0.12.6`.
