### ISSUE TITLE
gVisor dependency

### ISSUE THREAD

**Issue by cedws** [noisysockets/noisysockets#3]
Regarding this from the README:

>When you import Noisy Sockets Go Modules will attempt to use the gVisor master branch. The master branch cannot be used as a library, so you will need to explictly import the synthetic go branch in your project. If you don't do this you will see some strange build errors.

I seem to be able to import noisysockets into my project (`go mod tidy`/`go get`) without encountering this issue. Is this still relevant?

```
$ go version
go version go1.22.1 darwin/arm6
```

**Comment by dpeckett** [comment]
Ah good catch, it only occurs with `go get -u` as Go tries to upgrade the transitive gVisor dependency and ends up pulling the master branch. A plain `go get` will work without issues.

I've updated the documentation around that, it's a shame that gVisor can be such a pain but meh, netstack is totally worth the price of admission.
